### ISSUE TITLE
multi-gpu experiments

### ISSUE THREAD

**Issue by DanqingZ** [fmu2/PyTorch-MAML#1]
Hi Fangzhou, thanks for your codebase! With your codebase, I can reproduce the 5-way-1-shot mini-imagenet experiment with convnet4, single GPU training. However, when I switch to multiple GPUs and use the same parameter config file, the performance is not good.

* single GPU
```
meta-train set: torch.Size([5, 3, 84, 84]) (x800), 64
meta-val set: torch.Size([5, 3, 84, 84]) (x800), 16
num params: 32.9K
epoch 1, meta-train 1.5233|0.3346, meta-val 1.5522|0.3136, 2.8m 2.8m/14.1h
epoch 2, meta-train 1.4704|0.3686, meta-val 1.5350|0.3228, 2.8m 5.6m/14.1h
epoch 3, meta-train 1.4400|0.3909, meta-val 1.5029|0.3471, 2.8m 8.5m/14.1h
epoch 4, meta-train 1.4185|0.4017, meta-val 1.4785|0.3613, 2.8m 11.2m/14.1h
epoch 5, meta-train 1.3943|0.4204, meta-val 1.4737|0.3663, 2.8m 14.0m/14.0h
epoch 6, meta-train 1.3849|0.4223, meta-val 1.4879|0.3593, 2.8m 16.8m/14.0h
epoch 7, meta-train 1.3802|0.4281, meta-val 1.4652|0.3698, 2.7m 19.6m/14.0h
epoch 8, meta-train 1.3552|0.4411, meta-val 1.4479|0.3810, 2.8m 22.4m/14.0h
epoch 9, meta-train 1.3545|0.4401, meta-val 1.4700|0.3695, 2.9m 25.3m/14.0h
epoch 10, meta-train 1.3389|0.4502, meta-val 1.4644|0.3774, 2.8m 28.0m/14.0h
epoch 11, meta-train 1.3404|0.4474, meta-val 1.4527|0.3813, 2.8m 30.8m/14.0h
epoch 12, meta-train 1.3245|0.4556, meta-val 1.4342|0.3890, 2.8m 33.7m/14.0h
epoch 13, meta-train 1.3221|0.4567, meta-val 1.4344|0.3885, 2.8m 36.4m/14.0h
epoch 14, meta-train 1.3186|0.4571, meta-val 1.4400|0.3878, 2.8m 39.2m/14.0h
epoch 15, meta-train 1.3112|0.4636, meta-val 1.4453|0.3817, 2.8m 42.0m/14.0h
epoch 16, meta-train 1.3044|0.4680, meta-val 1.4152|0.4009, 2.8m 44.9m/14.0h
epoch 17, meta-train 1.2959|0.4737, meta-val 1.4172|0.4009, 2.8m 47.7m/14.0h
```
* multi GPU (the performance is always like below, didn't improve at all)
```
meta-train set: torch.Size([5, 3, 84, 84]) (x800), 64
meta-val set: torch.Size([5, 3, 84, 84]) (x800), 16
num params: 32.9K
epoch 1, meta-train 1.6346|0.1970, meta-val 1.6220|0.1994, 43.2s 43.2s/3.6h
epoch 2, meta-train 1.6246|0.2025, meta-val 1.6192|0.2012, 35.0s 1.3m/3.3h
epoch 3, meta-train 1.6215|0.1998, meta-val 1.6163|0.2021, 35.0s 1.9m/3.2h
epoch 4, meta-train 1.6185|0.1999, meta-val 1.6178|0.1984, 35.3s 2.5m/3.1h
epoch 5, meta-train 1.6165|0.2016, meta-val 1.6120|0.2018, 35.2s 3.1m/3.1h
epoch 6, meta-train 1.6121|0.2015, meta-val 1.6109|0.1986, 35.3s 3.7m/3.1h
epoch 7, meta-train 1.6100|0.2017, meta-val 1.6099|0.1968, 35.9s 4.3m/3.0h
epoch 8, meta-train 1.6100|0.1983, meta-val 1.6098|0.2012, 35.1s 4.8m/3.0h
epoch 9, meta-train 1.6098|0.2004, meta-val 1.6101|0.2003, 35.2s 5.4m/3.0h
epoch 10, meta-train 1.6097|0.1985, meta-val 1.6096|0.2010, 35.2s 6.0m/3.0h
epoch 11, meta-train 1.6096|0.2018, meta-val 1.6097|0.1988, 35.6s 6.6m/3.0h
epoch 12, meta-train 1.6097|0.2001, meta-val 1.6096|0.2000, 36.0s 7.2m/3.0h
epoch 13, meta-train 1.6095|0.2018, meta-val 1.6096|0.2003, 37.5s 7.8m/3.0h
epoch 14, meta-train 1.6097|0.1997, meta-val 1.6095|0.2007, 38.2s 8.5m/3.0h
epoch 15, meta-train 1.6096|0.1981, meta-val 1.6094|0.2025, 35.8s 9.1m/3.0h
epoch 16, meta-train 1.6095|0.1990, meta-val 1.6095|0.1986, 36.5s 9.7m/3.0h
epoch 17, meta-train 1.6096|0.1991, meta-val 1.6095|0.2006, 36.0s 10.3m/3.0h
```
I am wondering how can I get the multi GPU baseline working, did you change the parameters like the inner update rl and meta rl? And I am wondering why MAML is stuck at a local minimum for this multi GPU experiment. Many thanks and look forward to your reply!

**Comment by yzhang2016** [comment]
@DanqingZ  I tried the multi-GPU version. It works. 
epoch 1, meta-train 1.5246|0.3300, meta-val 1.5757|0.2976, 1.8m 1.8m/8.8h                                                                                                                                 
epoch 2, meta-train 1.4859|0.3598, meta-val 1.5349|0.3228, 1.7m 3.5m/8.7h                                                                                                                                 
epoch 3, meta-train 1.4603|0.3771, meta-val 1.5195|0.3328, 1.7m 5.2m/8.7h                                                                                                                                 
epoch 4, meta-train 1.4454|0.3855, meta-val 1.5130|0.3363, 1.7m 6.9m/8.6h                                                                                                                                 
epoch 5, meta-train 1.4242|0.4040, meta-val 1.4947|0.3535, 1.7m 8.6m/8.6h                                                                                                                                 
epoch 6, meta-train 1.4129|0.4049, meta-val 1.4892|0.3551, 1.7m 10.3m/8.6h

**Comment by fmu2** [comment]
DanqingZ and yzhang2016, thanks for your interest!

DanqingZ, from the estimated training time (~3h) you posted it looks like you used more than four GPUs. Since each batch has only four episodes/tasks by default, using >4 GPUs will distribute data from the same episode to more than one GPU, breaking the inner loop update. This also explains why yzhang2016 was able to get it work on possibly 2 GPUs. A quick fix is to increase the number of episodes per batch by updating the config file.

**Comment by DanqingZ** [comment]
@fmu2 I only used 2 GPUs, the command line is as below, I don't know what 2 gpus is running that fast :
```
python train.py --config configs/convnet4/mini-imagenet/5_way_1_shot/train_reproduce.yaml --gpu=0,1 --name convnet4_mini-imagenet_5_way_1_shot_test
```
Since the meta batch size = 4,  we cannot use more than four GPUS, or will get below error:
```
(pytorch_latest_p37) [ec2-user@ip-172-31-40-82 PyTorch-MAML-master]$ python train.py --config configs/convnet4/mini-imagenet/5_way_1_shot/train_reproduce.yaml --gpu=0,1,2,3,4,5 --name convnet4_mini-imagenet_5_way_1_shot_test
set gpu: 0,1,2,3,4,5
./save/convnet4_mini-imagenet_5_way_1_shot_test exists, remove? ([y]/n): y
meta-train set: torch.Size([5, 3, 84, 84]) (x800), 64
meta-val set: torch.Size([5, 3, 84, 84]) (x800), 16
num params: 32.9K
meta-train:   0%|                                                                                                                                                                                                     | 0/200 [00:00<?, ?it/s]Traceback (most recent call last):
  File "train.py", line 265, in <module>
    main(config)
  File "train.py", line 130, in main
    logits = model(x_shot, x_query, y_shot, inner_args, meta_train=True)
  File "/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 161, in forward
    outputs = self.parallel_apply(replicas, inputs, kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/parallel/data_parallel.py", line 171, in parallel_apply
    return parallel_apply(replicas, inputs, kwargs, self.device_ids[:len(replicas)])
  File "/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 86, in parallel_apply
    output.reraise()
  File "/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/_utils.py", line 428, in reraise
    raise self.exc_type(msg)
TypeError: Caught TypeError in replica 4 on device 4.
Original Traceback (most recent call last):
  File "/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/parallel/parallel_apply.py", line 61, in _worker
    output = module(*input, **kwargs)
  File "/home/ec2-user/anaconda3/envs/pytorch_latest_p37/lib/python3.7/site-packages/torch/nn/modules/module.py", line 727, in _call_impl
    result = self.forward(*input, **kwargs)
TypeError: forward() missing 4 required positional arguments: 'x_shot', 'x_query', 'y_shot', and 'inner_args'
```

**Comment by fmu2** [comment]
Did you change the number of workers for the data loaders? I recall I had a similar issue with num_workers > 1. I thought it has something to do with the DataLoader class itself. I was only able to get around it by setting num_workers to 0 or 1.

**Comment by DanqingZ** [comment]
When I use four gpus, I got similar results as 2 gpus:
```
(pytorch_latest_p37) [ec2-user@ip-172-31-40-82 PyTorch-MAML-master]$ python train.py --config configs/convnet4/mini-imagenet/5_way_1_shot/train_reproduce.yaml --gpu=0,1,2,3 --name convnet4_mini-imagenet_5_way_1_shot_test
set gpu: 0,1,2,3
./save/convnet4_mini-imagenet_5_way_1_shot_test exists, remove? ([y]/n): y
meta-train set: torch.Size([5, 3, 84, 84]) (x800), 64
meta-val set: torch.Size([5, 3, 84, 84]) (x800), 16
num params: 32.9K
epoch 1, meta-train 1.6345|0.1967, meta-val 1.6190|0.2004, 52.3s 52.3s/4.4h
epoch 2, meta-train 1.6259|0.2000, meta-val 1.6191|0.2003, 38.9s 1.5m/3.8h
epoch 3, meta-train 1.6246|0.2011, meta-val 1.6256|0.1989, 43.1s 2.2m/3.7h
epoch 4, meta-train 1.6186|0.1984, meta-val 1.6151|0.2037, 42.9s 3.0m/3.7h
epoch 5, meta-train 1.6129|0.1983, meta-val 1.6110|0.2004, 42.7s 3.7m/3.7h
epoch 6, meta-train 1.6106|0.1974, meta-val 1.6099|0.1999, 42.5s 4.4m/3.7h 
```
I am using AWS p4d 8 gpu ec2 instance, and I am using the default pytorch_latest_p37 conda environment
```
Python 3.7.6
torch 1.7.0+cu110 
```

**Comment by DanqingZ** [comment]
@fmu2, I didn't make any changes to the codebase. I just change --gpu and --name when I run experiments.

**Comment by DanqingZ** [comment]
@fmu2 , For 1 GPU, It took 2.8m for one epoch. 2 GPU, ~38s for one epoch. 4 GPU, ~43s for one epoch.
I am wondering why this is happening, based on my experience, 4 GPU experiment should be faster than 2 GPU experiment.

**Comment by fmu2** [comment]
I just ran the code with torch 1.7 using 2 GPUs and managed to reproduce your issue. Interestingly, the code works fine with torch 1.3 on 2 GPUs.

**Comment by DanqingZ** [comment]
@fmu2 , it looks like to there might be something wrong with the data loader. When you use torch 1.3 with more than 4 GPUs, are you able to get the experiments running? Mine got the above error I pasted.

**Comment by fmu2** [comment]
@DanqingZ I currently only have 2 available GPUs, but I think the error is expected. The first dimension of the input tensors is 4 (same as the number of episodes), so with >4 GPUs at least one receives no input, as the error message suggested.

**Comment by DanqingZ** [comment]
@fmu2 , sorry I am a bit confused by "with 2 GPUs and the number of episodes set to 1". Did you mean you can reproduce the error when 1) run with current config and with 2 GPUs; 2) change number of episodes to 1 and run on one GPU?

**Comment by fmu2** [comment]
@DanqingZ I set n_eposide=1 in the config file and used 2 GPUs for training. In this case only one GPU received data and the other didn't, which triggered the error. I did this to simulate the case where #GPUs > #episodes.

**Comment by DanqingZ** [comment]
I see, so here you mean the data loader error message. Thanks.

**Comment by fmu2** [comment]
@DanqingZ The code works fine with torch 1.3, cuda 10.1 at least on 2 GPUs, so you may want to try it out. Let me know if you find other problems.

**Comment by DanqingZ** [comment]
sure, thanks. I will also update if I can make the multi gpu version working for torch 1.7.
