### ISSUE TITLE
for resnet12 and resnet18

### ISSUE THREAD

**Issue by DanqingZ** [fmu2/PyTorch-MAML#3]
did your implementations train from scratch or load the pretrained weights like below? 
```
import torchvision.models as models
resnet18 = models.resnet18(pretrained=True)
```

**Comment by fmu2** [comment]
This implementation assumes randomly initialized ResNets. The conv layer in the stem has smaller receptive field since the input size is 84 (which is typical for meta-learning/few-shot learning), so pre-trained models would not work here.
