### ISSUE TITLE
wrong code.

### ISSUE THREAD

**Issue by George0726** [fmu2/PyTorch-MAML#8]
your ResNet18 is wrong.

**Comment by ZhangYikaii** [comment]
Are you referring to the **layers** of ResNet18 Blocks? I would appreciate your more detailed explanation.

**Comment by jihwankwak** [comment]
I guess @George0726's comment means that your implementation is missing some layers in each blocks. ResNet18 in Pytorch implementation is composed of multiple conv layers and residual connections between them but your implementation only has one conv layer and residual block
